mutation insertUsers($name:String!,$username:String!,$email:String!,$password:String!){
    insert_users(objects:{name:$name,username:$username,email:$email,password:$password}){
        affected_rows
        returning{
            name
            username
            email
        }
    }
}